package model;

public enum RequestType {
    ADD_ITEM,
    REMOVE_ITEM,
    LIST_ITEM_AVAILABILITY,
    PURCHASE_ITEM,
    FIND_ITEM,
    RETURN_ITEM,
    EXCHANGE_ITEM,
    ADD_WAIT_LIST,
    DATA_TRANSFER,
    MISSING_MESSAGE,
    FAILURE,
    FAILURE_AGREEMENT
}
